# Generated by Django 4.2 on 2023-05-07 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartify', '0008_cart_color_cart_productattr'),
        ('products', '0018_remove_productattribute_sizevariant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0002_auto_20230425_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.CharField(default=False, max_length=100)),
                ('payment_id', models.CharField(default=False, max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Successfully Delivered', 'Successfully Delivered')], default='Pending', max_length=100)),
                ('message', models.TextField(null=True)),
                ('tracking_number', models.CharField(default=False, max_length=100)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.FloatField(default=False)),
                ('product_qty', models.IntegerField()),
                ('size', models.CharField(default=False, max_length=100)),
                ('color', models.CharField(default=False, max_length=100)),
                ('total_price', models.FloatField(default=False)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartify.coupon')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('productattr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productattribute')),
            ],
        ),
    ]
