# Generated by Django 4.2 on 2023-05-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oders', '0002_remove_orderitem_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_price',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.FloatField(default=False),
        ),
    ]
