# Generated by Django 4.2 on 2023-05-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oders', '0004_remove_orderitem_total_price_alter_order_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.FloatField(default=False, null=True),
        ),
    ]
