# Generated by Django 4.2 on 2023-05-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oders', '0006_remove_orderitem_coupon_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Successfully Delivered', 'Successfully Delivered')], default='Pending', max_length=100),
        ),
    ]
