# Generated by Django 4.2 on 2023-05-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oders', '0008_orderitem_return_reason_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivered_date',
            field=models.DateField(null=True),
        ),
    ]
