# Generated by Django 4.2 on 2023-06-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oders', '0010_alter_order_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Successfully Delivered', 'Successfully Delivered'), ('Shipped', 'Shipped'), ('Return Approved', 'Return Approved')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Successfully Delivered', 'Successfully Delivered'), ('Shipped', 'Shipped'), ('Return Approved', 'Return Approved')], default='Pending', max_length=100, null=True),
        ),
    ]
