# Generated by Django 4.2 on 2023-06-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oders', '0012_order_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
    ]
