# Generated by Django 4.2 on 2023-06-21 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_review_added_at'),
        ('wishlist', '0002_auto_20230425_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='productattr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productattribute'),
        ),
    ]
