# Generated by Django 3.2.16 on 2023-04-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartify', '0003_auto_20230423_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=False),
        ),
    ]
