# Generated by Django 3.2.16 on 2023-04-24 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartify', '0004_cart_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(default=100)),
                ('minimum_amount', models.IntegerField(default=500)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='cartify.coupon'),
        ),
    ]
