# Generated by Django 4.2 on 2023-05-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartify', '0008_cart_color_cart_productattr'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_used',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
