# Generated by Django 4.2 on 2023-06-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartify', '0009_coupon_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
