# Generated by Django 4.2 on 2023-05-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('IFSC', models.CharField(max_length=50)),
                ('acccount_number', models.CharField(max_length=50)),
                ('Upi', models.CharField(max_length=50)),
            ],
        ),
    ]
