# Generated by Django 4.2 on 2023-06-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
