# Generated by Django 4.2 on 2023-07-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_wallet_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('INDIA', 'India'), ('UK', 'United Kingdom')], max_length=150),
        ),
    ]
