# Generated by Django 3.2.16 on 2023-04-04 06:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color_variant',
            new_name='colorvariant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_variant',
            new_name='sizevariant',
        ),
        migrations.RemoveField(
            model_name='colorvariant',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sizevariant',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='product')),
                ('colorVariant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.colorvariant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('sizevariant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sizevariant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
