# Generated by Django 3.2.16 on 2023-04-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230404_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='color_code',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
