# Generated by Django 3.2.16 on 2023-04-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_colorvariant_color_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colorvariant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_desription',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizevariant',
        ),
        migrations.AddField(
            model_name='product',
            name='Detail_desription',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_discription',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keyword',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='orginal_price',
            field=models.FileField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.FileField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='small_desription',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default,1=Hidden'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False, help_text='0=default, 1=Hidden'),
        ),
    ]
