# Generated by Django 3.2.16 on 2023-04-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20230405_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='price',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='orginal_price',
            field=models.FloatField(default=False),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='selling_price',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='orginal_price',
            field=models.FloatField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(default=False),
        ),
    ]
