# Generated by Django 3.2.16 on 2023-04-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230418_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorvariant',
            name='color_code',
            field=models.CharField(default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='colorvariant',
            name='color_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
