# Generated by Django 4.2 on 2023-04-27 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='image',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='quantity',
            field=models.IntegerField(default=False),
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='sizevariant',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.productattribute'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='sizevariant',
            field=models.ManyToManyField(to='products.sizevariant'),
        ),
    ]
