# Generated by Django 4.2 on 2023-04-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productimage_product_attribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
    ]
