# Generated by Django 4.2 on 2023-04-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='color_image',
            field=models.ImageField(null=True, upload_to='catgories'),
        ),
    ]
