# Generated by Django 4.2 on 2023-04-27 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_colorvariant_color_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorvariant',
            name='color_image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product_attribute',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productimage'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to='product'),
        ),
    ]
