# Generated by Django 4.2 on 2023-04-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_colorvariant_color_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='images',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.productattribute'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product'),
        ),
    ]
