# Generated by Django 4.2 on 2023-06-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_review_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
