# Generated by Django 4.2 on 2023-06-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_category_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='offer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
