# Generated by Django 4.2 on 2023-07-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_category_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='front_image',
            name='img2',
            field=models.ImageField(default=True, null=True, upload_to='front_image'),
        ),
    ]
