# Generated by Django 4.2 on 2023-07-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_front_image_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front_image',
            name='img2',
            field=models.ImageField(null=True, upload_to='front_image'),
        ),
    ]
